// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_kLO-rQhBYanIb7wJGUv4gceOpCYB24',
    appId: '1:1082024102440:android:efe5553504f9345185031d',
    messagingSenderId: '1082024102440',
    projectId: 'zherdeshapplication',
    storageBucket: 'zherdeshapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB1_TAUq_Uht_DpkorTWU1ie4v6VWlC-o',
    appId: '1:1082024102440:ios:aa56389ddd1ff9b485031d',
    messagingSenderId: '1082024102440',
    projectId: 'zherdeshapplication',
    storageBucket: 'zherdeshapplication.appspot.com',
    androidClientId: '1082024102440-2t4sc6jp03o30qfo2ge9ua740m1d4otu.apps.googleusercontent.com',
    iosClientId: '1082024102440-8fpf78bkffnpecskra138bvj0isi135l.apps.googleusercontent.com',
    iosBundleId: 'com.zherdeshapp.zherdeshmobileapplication',
  );
}
